//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC_03_QuanLyVatTu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuanLyVatTuRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuanLyVatTuRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFC_03_QuanLyVatTu.Resources.QuanLyVatTuRes", typeof(QuanLyVatTuRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap ngay nhap theo dinh dang (yyyy/MM/dd)!.
        /// </summary>
        internal static string ErrorNgayNhap {
            get {
                return ResourceManager.GetString("ErrorNgayNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap ngay nhap theo dinh dang (yyyy/MM/dd)!.
        /// </summary>
        internal static string ErrorNgayXuat {
            get {
                return ResourceManager.GetString("ErrorNgayXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap vao la so!.
        /// </summary>
        internal static string ErrorNhapSo {
            get {
                return ResourceManager.GetString("ErrorNhapSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach trong!.
        /// </summary>
        internal static string LogDanhSachTrong {
            get {
                return ResourceManager.GetString("LogDanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay vat tu!.
        /// </summary>
        internal static string LogKhongTimThayVatTu {
            get {
                return ResourceManager.GetString("LogKhongTimThayVatTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong khong du!.
        /// </summary>
        internal static string LogSoLuongKhongDu {
            get {
                return ResourceManager.GetString("LogSoLuongKhongDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh cong!.
        /// </summary>
        internal static string LogThanhCong {
            get {
                return ResourceManager.GetString("LogThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma phieu: .
        /// </summary>
        internal static string MaPhieu {
            get {
                return ResourceManager.GetString("MaPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay nhap (nam/thang/ngay): .
        /// </summary>
        internal static string NgayNhap {
            get {
                return ResourceManager.GetString("NgayNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay xuat (nam/thang/ngay):.
        /// </summary>
        internal static string NgayXuat {
            get {
                return ResourceManager.GetString("NgayXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap phieu nhap ID:.
        /// </summary>
        internal static string PhieuNhapId {
            get {
                return ResourceManager.GetString("PhieuNhapId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap phieu xuat ID: .
        /// </summary>
        internal static string PhieuXuatId {
            get {
                return ResourceManager.GetString("PhieuXuatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong nhap: .
        /// </summary>
        internal static string SoLuongNhap {
            get {
                return ResourceManager.GetString("SoLuongNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong ton: .
        /// </summary>
        internal static string SoLuongTon {
            get {
                return ResourceManager.GetString("SoLuongTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong xuat: .
        /// </summary>
        internal static string SoLuongXuat {
            get {
                return ResourceManager.GetString("SoLuongXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten vat tu: .
        /// </summary>
        internal static string TenVatTu {
            get {
                return ResourceManager.GetString("TenVatTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap tieu de: .
        /// </summary>
        internal static string TieuDe {
            get {
                return ResourceManager.GetString("TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap vat tu ID: .
        /// </summary>
        internal static string VatTuId {
            get {
                return ResourceManager.GetString("VatTuId", resourceCulture);
            }
        }
    }
}
